#!/bin/bash

readonly root=$(dirname "$0")
result=0

for script in F I+ I-
do
  if (cd "$root/$script" && go install)
  then
    echo "$script installed"
  else
    echo "can't install $script"
    result=255
  fi
done

exit $result